### ISSUE TITLE
in configuration file : ```min_nb_good_samples_after_outliers_removal ```

### ISSUE THREAD

**Issue by melvanhove** [martin-obs/OVERLAP_PROBE_EPROFILE#2]
I think there is a part repeating itself, once in ```calculate_overlap_automatic_structured2.m``` and once in ```read_overlap_cor_v7_eprofile.m```; since I've been working with this value set at 20 instead of 10, in the code ```read_overlap_cor_v7_eprofile.m```, we can also set it at 20 instead of 10 in the preliminary configurations values.

**Comment by martin-obs** [comment]
No problem - I'll keep it set at 20.

**Comment by martin-obs** [comment]
I have removed this test from the part of the code that creates the daily overlap csv files from L1 data - so not a csv is created even if there is only one good sample. The test is now applied in the temperature model builder. This way the min number of good samples that is acceptable can be chosen at the end of the processing chain (i.e. when the temperature model is about to be created) rather than having to re-run all the daily files.
